### ISSUE TITLE
Dear developers,hope you can add Simplified Chinese support

### ISSUE THREAD

**Issue by lexlong2007** [fairbird/NewVirtualKeyBoard#13]
I added the code.
('Chinese', 'zh_CN', '00000804'),it seems that the download is not successful,the download is not Chinese,thank you!

`('Chinese', 'zh_CN', '00000404') `

I didn't find the code for the keyboard configuration in Simplified Chinese, I don't know what this is.  ex:
https://learn.microsoft.com/en-gb/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs?view=windows-11

thank you!

**Comment by fairbird** [comment]
https://github.com/fairbird/NewVirtualKeyBoard/commit/bbf923ec071ae73220ee1fa23eea58babbbb3753
